export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import '../styles/globals.css'
import dbConnect from '@/services/dbConnect'
import { AuthProvider } from '@/providers/authProvider'
import { Toaster } from '@/components/ui/sonner'
export default async function RootLayout({ children }) {
  await dbConnect()
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {children}
          <Toaster richColors position="top-center"/>
        </AuthProvider>
      </body>
    </html>
  )
}
