export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import { Toaster } from 'react-hot-toast'
import '../globals.css'
import dbConnect from '@/services/dbConnect'
import { AuthProvider } from '@/providers/authProvider'
export default async function RootLayout({ children }) {
  await dbConnect()
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {children}
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  )
}
