export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import { Toaster } from 'react-hot-toast'
import '../globals.css'
import dbConnect from '@/services/dbConnect'
export default async function RootLayout({ children }) {
  await dbConnect()
  return (
    <html lang="en">
      <body>
        {children}
        <Toaster />
      </body>
    </html>
  )
}
